In [ ]:
#1234567890123456789012345678901234567890123456789012345678901234567890123456789

# Module 5 - Working with Numpy Arrays

## Table of Contents

- 5.1 **[Numpy 1D Arrays](#5.1)**
    - 5.1.1 [Creating a Numpy Array](#5.1.1)
        - 5.1.1.1 [Type](#5.1.1.1)
        - 5.1.1.2 [Slicing](#5.1.1.2)
        - 5.1.1.3 [Assign Value](#5.1.1.3)
        - 5.1.1.4 [Assign Value Using List](#5.1.1.4)
        - 5.1.1.5 [Other Attributes](#5.1.1.4)
    - 5.1.2 [Numpy Array Operations](#5.1.2)
        - 5.1.2.1 [Array Addition](#5.1.2.1)
        - 5.1.2.2 [Array Multiplication](#5.1.2.2)
        - 5.1.2.3 [Product of Two Numpy Arrays](#5.1.2.3)
        - 5.1.2.4 [Dot Product](#5.1.2.4)
        - 5.1.2.5 [Adding Constant to a Numpy Array](#5.1.2.5)
    - 5.1.3 [Mathematical Functions](#5.1.3)
    - 5.1.4 [Linspace](#5.1.4)
- 5.2 **[Numpy 2D Arrays](#5.2)**
- 5.3 **[Numpy Quiz](#5.3)**

## 5.1 Numpy 1D Arrays <a id='5.1'></a>

In [1]:
# Import libraries required for numpy

import time
import sys
import numpy as np

import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# Plotting functions

def Plotvec1(u, z, v):
    
    ax = plt.axes()
    ax.arrow(0, 0, *u, head_width=0.05, color='r', head_length=0.1)
    plt.text(*(u + 0.1), 'u')
    
    ax.arrow(0, 0, *v, head_width=0.05, color='b', head_length=0.1)
    plt.text(*(v + 0.1), 'v')
    ax.arrow(0, 0, *z, head_width=0.05, head_length=0.1)
    plt.text(*(z + 0.1), 'z')
    plt.ylim(-2, 2)
    plt.xlim(-2, 2)

def Plotvec2(a,b):
    ax = plt.axes()
    ax.arrow(0, 0, *a, head_width=0.05, color ='r', head_length=0.1)
    plt.text(*(a + 0.1), 'a')
    ax.arrow(0, 0, *b, head_width=0.05, color ='b', head_length=0.1)
    plt.text(*(b + 0.1), 'b')
    plt.ylim(-2, 2)
    plt.xlim(-2, 2)

### 5.1.1 Creating a Numpy Array <a id='5.1.1'></a>

In [56]:
# After importing numpy library (done above) create a numpy array

vault = np.array([4, 76, 101, 94, 54])

In [8]:
# Each element can be accessed using the index

print('vault[0]:', a[0])

vault[0]: 4


#### 5.1.1.1 Type <a id='5.1.1.1'></a>

In [9]:
# Check the type of the array

type(vault)

numpy.ndarray

In [10]:
# Check the type of data contained in the array

vault.dtype

dtype('int32')

In [44]:
# Create a numpy array containing real numbers / float

ammo_types = np.array([.35, .44, 40, .308, 50])

In [31]:
# Check type of array

type(ammo_types)

numpy.ndarray

In [32]:
# Check value type

ammo_types.dtype

dtype('float64')

#### 5.1.1.2 Slicing <a id='5.1.1.2'></a>

In [33]:
# Slicing a numpy array

a = ammo_types[1:4]
a

array([ 0.44 , 40.   ,  0.308])

#### 5.1.1.3 Assign Value <a id='5.1.1.3'></a>

In [34]:
# Assign a new value to an element via index

ammo_types[2] = 5.56
ammo_types

array([ 0.35 ,  0.44 ,  5.56 ,  0.308, 50.   ])

In [35]:
# Assign new values to two elements

ammo_types[:2] = .38, .45
ammo_types

array([ 0.38 ,  0.45 ,  5.56 ,  0.308, 50.   ])

#### 5.1.1.4 Assign Values Using List <a id='5.1.1.4'></a>

In [57]:
# Create the index list

select = [0, 2, 3]

In [58]:
# Use the list to select elements

b = vault[select]
b

array([  4, 101,  94])

In [60]:
# Assign the specified elements to a new value

vault[select] = 10
vault

array([10, 76, 10, 10, 54])

#### 5.1.1.5 Other Attributes <a id='5.1.1.5'></a>

In [61]:
# Create a numpy array

a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [62]:
# Get the size of numpy array

a.size

5

In [63]:
# Get the number of dimensions/rank of numpy array

a.ndim

1

### 5.1.2 Numpy Array Operations <a id='5.1.2'></a>

#### 5.1.2.1 Array Addition <a id='5.1.2.1'></a>

#### 5.1.2.2 Array Multiplication <a id='5.1.2.2'></a>

#### 5.1.2.3 Product of Two Numpy Arrays <a id='5.1.2.3'></a>

#### 5.1.2.4 Dot Product <a id='5.1.2.4'></a>

#### 5.1.2.5 Adding Constant to a Numpy Array <a id='5.1.2.5'></a>

### 5.1.3 Mathematical Functions <a id='5.1.3'></a>

## 5.3 Numpy Quiz

In [4]:
# Cast a numpy array

import numpy as np
a = np.array([1, 2, 3, 4, 5])

In [10]:
# Check the type

type(a)

numpy.ndarray

In [11]:
# Determine shape of the array

a.shape

(5,)

In [6]:
# Type of data in the array

a.dtype

dtype('int32')

In [12]:
# Find the mean of the array

a.mean()

3.0

In [13]:
# What is the result of the following

np.array([1,-1])*np.array([1,1])

array([ 1, -1])

In [14]:
# What is the result of the following

np.dot(np.array([1,-1]), np.array([1,1]))

0